openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Pet Store API'
  description: 'This is a simple API for a pet store.'
  termsOfService: 'http://example.com/terms/'
  contact:
    name: 'API Support'
    url: 'http://www.example.com/support'
    email: 'support@example.com'
  license:
    name: 'Apache 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://api.example.com/v1'
    description: 'Production server (uses live data)'
  - url: 'http://staging-api.example.com'
    description: 'Staging server (uses test data)'
paths:
  /pets:
    get:
      summary: 'List all pets'
      operationId: 'listPets'
      tags:
        - 'pets'
      parameters:
        - name: 'limit'
          in: 'query'
          description: 'How many items to return at one time'
          required: false
          schema:
            type: 'integer'
            format: 'int32'
      responses:
        '200':
          description: 'An array of pets.'
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Pet'
        'default':
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: 'object'
      required:
        - 'id'
        - 'name'
      properties:
        id:
          type: 'integer'
          format: 'int64'
        name:
          type: 'string'
        tag:
          type: 'string'
    Error:
      type: 'object'
      required:
        - 'code'
        - 'message'
      properties:
        code:
          type: 'integer'
          format: 'int32'
        message:
          type: 'string'
  securitySchemes:
    api_key:
      type: 'apiKey'
      name: 'api_key'
      in: 'header'
security:
  - api_key: []
